version: "3.7"

services :

  gitlab-web:
    image: 'gitlab/gitlab-ce:${GITLAB_VERSION:-latest}'
    restart: always
    container_name: gitlab-web
    hostname: gitlab.chimera
    ports:
      - '20:20'
    networks:
      - "chimera"
    volumes:
      - './data/backups:/var/opt/gitlab/backups'
      - './data/data:/var/opt/gitlab'
      - './data/web-config:/etc/gitlab'
      - './data/logs:/var/log/gitlab'

    environment:
      TZ: Europe/Paris
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.${DOMAIN_NAME}'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['redirect_http_to_https'] = true
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "${GITLAB_SMTP_ADDRESS}"
        gitlab_rails['smtp_port'] = ${GITLAB_SMTP_PORT}
        gitlab_rails['smtp_user_name'] = "${GITLAB_SMTP_USER_NAME}"
        gitlab_rails['smtp_password'] = "${GITLAB_SMTP_PASSWORD}"
        gitlab_rails['smtp_domain'] = "${GITLAB_SMTP_DOMAIN}"
        gitlab_rails['smtp_authentication'] = "${GITLAB_SMTP_AUTHENTICATION}"
        gitlab_rails['smtp_enable_starttls_auto'] = ${GITLAB_SMTP_STARTTLS}
        gitlab_rails['smtp_tls'] = ${GITLAB_SMTP_TLS}
        gitlab_rails['smtp_openssl_verify_mode'] = '${GITLAB_SMTP_VERIFY_MODE}'

  gitlab-runner :
    image: 'gitlab/gitlab-runner:alpine'
    restart: on-failure
    container_name: gitlab-runner
    hostname: gitlab-runner
    networks:
      - "chimera"
    volumes :
      - './data/runner-config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'

networks:
  chimera:
    external: true