version: '3.1'

services:

  service_maria:
    image: mariadb
    restart: unless-stopped
    container_name: service_maria
    hostname: maria
    networks:
      - "chimera"
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-}"
    volumes :
      - './data/mysql:/var/lib/mysql:delegated'

  service_phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    container_name: service_phpmyadmin
    hostname: phpmyadmin.chimera
    networks:
      - "chimera"
    environment:
      PMA_HOST: "maria"
      UPLOAD_LIMIT: 20M

networks:
  chimera:
    external: true