version: "3.7"

services :
  
  core_nginx :
    build : nginx-image
    restart: on-failure
    container_name: core_nginx
    hostname: nginx
    ports :
      - '80:80'
      - '443:443'
    networks:
      - "chimera"
    volumes :
      - './data/config:/root/config'
      - './data/logs:/var/log/nginx/'
      - './data/html:/usr/share/nginx/html/'
      - '/etc/letsencrypt/:/etc/letsencrypt/'

networks:
  chimera:
    external: true