version: "3.7"

services :
  
  nginx :
    build : nginx-image
    restart: on-failure
    container_name: nginx
    hostname: nginx
    ports :
      - '80:80'
      - '443:443'
    networks:
      - "chimera"
    volumes :
      - './data/config:/root/config'
      - './data/logs:/var/log/nginx/'

networks:
  chimera:
    external: true